### ISSUE TITLE
Support for other devices by same vendor

### ISSUE THREAD

**Issue by kinafu** [patrickmarlier/etes603-dev#2]
I just found your driver for the device `1c7a:0603`.

The fingerprint sensor `1c7a:0570` is also not officially supported by the vendor LighTuning Technology or even Acer (my notebook's brand).
[Output from lsusb -D](https://gist.github.com/kinafu/5ad47bf35752d4270dd897b7a01b1f8c)

I wonder, if the devices might be similar and your driver could also work / get easily adapted for the mentioned device.

I didn't test not compiled your driver for this device yet. Until now, there's just the idea :blush: .

**Comment by patrickmarlier** [comment]
I should check https://github.com/indev29/egis0570 .
I had a quick look in this repository and it seems that the protocol is different.
